### ISSUE TITLE
CSS leaks from bundled webcompoment

### ISSUE THREAD

**Issue by CColon1** [umbopepato/rollup-plugin-postcss-lit#40]
I'm not sure if this is an issue WIth this plugin, PostCSS, rollup, or If I just don't know what I'm doing. However I'm injecting a web component in to a wordpress site. The bundled component uses it's own css, however that css is effecting the rest of the site. My understanding was that the components css should be sandboxed in the shadow dom. Any tips would be greatly appreciated.

**Comment by umbopepato** [comment]
Hi @CColon1!
Can you please share you rollup configuration?
My guess is that you probably haven't disabled [style injection](https://github.com/egoist/rollup-plugin-postcss#inject) in `rollup-plugin-postcss`'s options:

```js
plugins: [
  postcss({
    inject: false,
  }),
  ...
],
```

**Comment by jlesquembre** [comment]
I'm having the same issue, in my case, it's because I'm using Vite. Looks like Vite is injecting the styles in index.html

**Comment by umbopepato** [comment]
Hey @jlesquembre! That's Vite's default behaviour and unfortunately as of now it cannot be disabled. See https://github.com/vitejs/vite/issues/3246 and https://github.com/vitejs/vite/pull/2148#issuecomment-784738508

**Comment by jlesquembre** [comment]
@umbopepato thanks for the links, let's see if it gets fixed in Vite

**Comment by vmadman** [comment]
FYI, pretty sure this was fixed in Vite. You just need to add `?inline` after the scss imports.

e.g.
```
import styles from './my-styles.scss?inline';
```

See: https://github.com/vitejs/vite/commit/e1de8a888ea9adb9dc415cf74aec43dfa83aa526

**Comment by umbopepato** [comment]
Thanks for the heads up @vmadman, I updated the README! 🙂
