### ISSUE TITLE
Plugin is incompatible with Storybook using Vite@2.9.7

### ISSUE THREAD

**Issue by troyvassalotti** [umbopepato/rollup-plugin-postcss-lit#50]
With vite's update to v2.9.7, the plugin's default settings no longer work when used in conjunction with [@storybook/builder-vite](https://github.com/storybookjs/builder-vite).

A minimal reproducible example can be found here: https://github.com/troyvassalotti/storybook-vite-plugin-mre with steps on how to reproduce and the error that is happening.

It seems that Vite may have changed how CSS imports work and it is creating an issue when trying to run a Storybook dev server. This issue is related to #49. In order for the plugin to work with Storybook so we can import SASS into our Lit components, we need to specifically `include` only SASS files. We lose the option to `include` standard CSS files after the Vite update.

**Comment by umbopepato** [comment]
Thanks for investigating @IanVS! I'll try and handle that AST format as well.
What surprises me is that in @troyvassalotti's example the css code is sent to the plugin as raw unprocessed text...

**Comment by bluwy** [comment]
Note The linked PRs has been reverted due to other regressions caused. See https://github.com/vitejs/vite/pull/8874

**Comment by jrencz** [comment]
Just for the record: adjusting default `include` pattern solved the problem for me

https://github.com/umbopepato/rollup-plugin-postcss-lit/blob/303e1b0e9a58bb53b7678c7d8d46a58aab79c6ec/index.ts#L32

```ts
include: '**/*.{css,sss,pcss,styl,stylus,sass,scss,less}?(*)'
```

Maybe a way to go would be to introduce an option allowing to match without query (and use it by default)

**Comment by umbopepato** [comment]
Cool @jrencz, let's change the default `include` to that one then. Feel free to to open a PR if you want!
As for the additional option, I'd say changing the `include` option directly should be enough, no?

**Comment by jrencz** [comment]
It should, but what I meant was: instead of matching whole `id`, let's instead extract the path out of it and filter the paths. That would make it impossible to match query if one wanted to, as one can now

Additional flag/option would allow users to revert to the native way (i.e. with query) if needed.

**Comment by umbopepato** [comment]
Is anyone still experiencing this problem? I cannot reproduce it with recent versions of `vite` and `@storybook/builder-vite`

**Comment by sr258** [comment]
@umbopepato I've recently had the issue when using Storybook 7.4 and rollup-plugin-postcss-lit 2.0.0. I've updated to Storybook 7.5 and rollup-plugin-postcss-lit 2.1.0 and the issue has disappeared! Thanks for fixing it!
